### PR TITLE
feat: test branch dont delete ever

### PR DESCRIPTION
**Pull request by raisedadead**

### CODE REVIEW

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `earthian` is not a valid language directory | guide/earthian/html/index.md |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | Upper case characters found in the file path, all file paths must be lower case | guide/english/bootstrap/3D/index.md |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `random-file-name` is not a valid file name, please use `index.md` | guide/english/bootstrap/random-file-name |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `_inde.md` is not a valid file name, please use `index.md` | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 2 | Invalid character found in a directory name, please use `-` as separators | guide/english/algorithms/algorithm-design patterns/_inde.md |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by raisedadead** [comment]
GOOOOOOOOD GOING!

**Comment by raisedadead** [comment]
OKAAY!

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `earthian` is not a valid language directory | guide/earthian/html/index.md |
| 2 | `_inde.md` is not a valid file name, please use `index.md` | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 3 | Invalid character found in a directory name, please use `-` as separators | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 4 | Upper case characters found in the file path, all file paths must be lower case | guide/english/bootstrap/3D/index.md |
| 5 | `random-file-name` is not a valid file name, please use `index.md` | guide/english/bootstrap/random-file-name |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `earthian` is not a valid language directory | guide/earthian/html/index.md |
| 2 | `_inde.md` is not a valid file name, please use `index.md` | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 3 | Invalid character found in a directory name, please use `-` as separators | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 4 | Upper case characters found in the file path, all file paths must be lower case | guide/english/bootstrap/3D/index.md |
| 5 | `random-file-name` is not a valid file name, please use `index.md` | guide/english/bootstrap/random-file-name |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `earthian` is not a valid language directory | guide/earthian/html/index.md |
| 2 | `_inde.md` is not a valid file name, please use `index.md` | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 3 | Invalid character found in a directory name, please use `-` as separators | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 4 | Upper case characters found in the file path, all file paths must be lower case | guide/english/bootstrap/3D/index.md |
| 5 | `random-file-name` is not a valid file name, please use `index.md` | guide/english/bootstrap/random-file-name |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `earthian` is not a valid language directory | guide/earthian/html/index.md |
| 2 | `_inde.md` is not a valid file name, please use `index.md` | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 3 | Invalid character found in a directory name, please use `-` as separators | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 4 | Upper case characters found in the file path, all file paths must be lower case | guide/english/bootstrap/3D/index.md |
| 5 | `random-file-name` is not a valid file name, please use `index.md` | guide/english/bootstrap/random-file-name |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `earthian` is not a valid language directory | guide/earthian/html/index.md |
| 2 | `_inde.md` is not a valid file name, please use `index.md` | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 3 | Invalid character found in a directory name, please use `-` as separators | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 4 | Upper case characters found in the file path, all file paths must be lower case | guide/english/bootstrap/3D/index.md |
| 5 | `random-file-name` is not a valid file name, please use `index.md` | guide/english/bootstrap/random-file-name |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `earthian` is not a valid language directory | guide/earthian/html/index.md |
| 2 | `_inde.md` is not a valid file name, please use `index.md` | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 3 | Invalid character found in a directory name, please use `-` as separators | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 4 | Upper case characters found in the file path, all file paths must be lower case | guide/english/bootstrap/3D/index.md |
| 5 | `random-file-name` is not a valid file name, please use `index.md` | guide/english/bootstrap/random-file-name |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `earthian` is not a valid language directory | guide/earthian/html/index.md |
| 2 | `_inde.md` is not a valid file name, please use `index.md` | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 3 | Invalid character found in a directory name, please use `-` as separators | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 4 | Upper case characters found in the file path, all file paths must be lower case | guide/english/bootstrap/3D/index.md |
| 5 | `random-file-name` is not a valid file name, please use `index.md` | guide/english/bootstrap/random-file-name |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `earthian` is not a valid language directory | guide/earthian/html/index.md |
| 2 | `_inde.md` is not a valid file name, please use `index.md` | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 3 | Invalid character found in a directory name, please use `-` as separators | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 4 | Upper case characters found in the file path, all file paths must be lower case | guide/english/bootstrap/3D/index.md |
| 5 | `random-file-name` is not a valid file name, please use `index.md` | guide/english/bootstrap/random-file-name |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `earthian` is not a valid language directory | guide/earthian/html/index.md |
| 2 | `_inde.md` is not a valid file name, please use `index.md` | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 3 | Invalid character found in a directory name, please use `-` as separators | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 4 | Upper case characters found in the file path, all file paths must be lower case | guide/english/bootstrap/3D/index.md |
| 5 | `random-file-name` is not a valid file name, please use `index.md` | guide/english/bootstrap/random-file-name |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `earthian` is not a valid language directory | guide/earthian/html/index.md |
| 2 | `_inde.md` is not a valid file name, please use `index.md` | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 3 | Invalid character found in a directory name, please use `-` as separators | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 4 | Upper case characters found in the file path, all file paths must be lower case | guide/english/bootstrap/3D/index.md |
| 5 | `random-file-name` is not a valid file name, please use `index.md` | guide/english/bootstrap/random-file-name |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `earthian` is not a valid language directory | guide/earthian/html/index.md |
| 2 | `_inde.md` is not a valid file name, please use `index.md` | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 3 | Invalid character found in a directory name, please use `-` as separators | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 4 | Upper case characters found in the file path, all file paths must be lower case | guide/english/bootstrap/3D/index.md |
| 5 | `random-file-name` is not a valid file name, please use `index.md` | guide/english/bootstrap/random-file-name |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Comment by RandellDawson** [comment]
Hi @raisedadead,

Thanks for this pull request (PR).

Unfortunately, these changes have failed some of our recommended guidelines. Please correct the issue(s) listed below, so we can consider merging your content.

| Issue | Description | File Path |
| :---: | --- | --- |
| 1 | `earthian` is not a valid language directory | guide/earthian/html/index.md |
| 2 | `_inde.md` is not a valid file name, please use `index.md` | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 3 | Invalid character found in a directory name, please use `-` as separators | guide/english/algorithms/algorithm-design patterns/_inde.md |
| 4 | Upper case characters found in the file path, all file paths must be lower case | guide/english/bootstrap/3D/index.md |
| 5 | `random-file-name` is not a valid file name, please use `index.md` | guide/english/bootstrap/random-file-name |

P.S: I am just friendly bot. You should reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for more help.

**Pull request closed without merging**
